service: screenshoter

package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  runtime: nodejs6.10

functions:
  saveWebsiteScreenshot:
    handler: handler.saveWebsiteScreenshot
    memorySize: 128
    timeout: 30
    package:
      include:
        - handler.js
